export default [
  {
    id: 1,
    firstName: 'Ana',
    lastName: 'Martínez',
    email: 'ana.martinez@example.com',
    phoneNumber: '1234567890',
    birthDate: '14/01/1994',
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 1,
    notes: 'Prefers direct flights.',
  },
  {
    id: 2,
    firstName: 'Luis',
    lastName: 'González',
    email: 'luis.gonzalez@example.com',
    phoneNumber: '0987654321',
    birthDate: '22/11/1987',
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 2,
  },
  {
    id: 3,
    firstName: 'María',
    lastName: 'Rodríguez',
    email: 'maria.rodriguez@example.com',
    phoneNumber: '1122334455',
    birthDate: '05/07/2001',
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 3,
    notes: 'Allergic to peanuts.',
  },
  {
    id: 4,
    firstName: 'Jorge',
    lastName: 'López',
    email: 'jorge.lopez@example.com',
    phoneNumber: '5566778899',
    birthDate: '09/02/1996',
    gender: 'Male',
    paymentMethod: 'Paypal',
    travelId: 4,
  },
  {
    id: 5,
    firstName: 'Sofía',
    lastName: 'Pérez',
    email: 'sofia.perez@example.com',
    phoneNumber: '2233445566',
    birthDate: '12/12/1993',
    gender: 'Female',
    paymentMethod: 'Revolut',
    travelId: 5,
    notes: 'Vegetarian meal preference.',
  },
  {
    id: 6,
    firstName: 'Carlos',
    lastName: 'Navarro',
    email: 'carlos.navarro@example.com',
    phoneNumber: '6677889900',
    birthDate: '27/04/1997',
    gender: 'Male',
    paymentMethod: 'Bank transfer',
    travelId: 1,
  },
  {
    id: 7,
    firstName: 'Beatriz',
    lastName: 'Díaz',
    email: 'beatriz.diaz@example.com',
    phoneNumber: '9988776655',
    birthDate: '17/03/1988',
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 2,
    notes: 'Requires wheelchair access.',
  },
  {
    id: 8,
    firstName: 'David',
    lastName: 'Jiménez',
    email: 'david.jimenez@example.com',
    phoneNumber: '5544332211',
    birthDate: '29/06/1978',
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 3,
  },
  {
    id: 9,
    firstName: 'Elena',
    lastName: 'Suárez',
    email: 'elena.suarez@example.com',
    phoneNumber: '1122443355',
    birthDate: '15/05/1998',
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 4,
    notes: 'Prefers aisle seat.',
  },
  {
    id: 10,
    firstName: 'Fernando',
    lastName: 'Torres',
    email: 'fernando.torres@example.com',
    phoneNumber: '5566887799',
    birthDate: '03/08/1992',
    gender: 'Male',
    paymentMethod: 'Paypal',
    travelId: 5,
  },
  {
    id: 11,
    firstName: 'Gabriela',
    lastName: 'Luna',
    email: 'gabriela.luna@example.com',
    phoneNumber: '6655443322',
    birthDate: '19/09/1994',
    gender: 'Female',
    paymentMethod: 'Revolut',
    travelId: 1,
  },
  {
    id: 12,
    firstName: 'Héctor',
    lastName: 'Vega',
    email: 'hector.vega@example.com',
    phoneNumber: '2233554477',
    birthDate: '07/02/1986',
    gender: 'Male',
    paymentMethod: 'Bank transfer',
    travelId: 2,
  },
  {
    id: 13,
    firstName: 'Irene',
    lastName: 'Molina',
    email: 'irene.molina@example.com',
    phoneNumber: '7788990011',
    birthDate: '20/10/1999',
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 3,
    notes: 'Non-smoker.',
  },
  {
    id: 14,
    firstName: 'Javier',
    lastName: 'Herrera',
    email: 'javier.herrera@example.com',
    phoneNumber: '8899001122',
    birthDate: '04/07/1985',
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 4,
  },
  {
    id: 15,
    firstName: 'Laura',
    lastName: 'Sánchez',
    email: 'laura.sanchez@example.com',
    phoneNumber: '4455667788',
    birthDate: '18/08/1991',
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 5,
    notes: 'Vegan meals only.',
  },
]
