export default [
  {
    id: 1,
    firstName: 'Ana',
    lastName: 'Martínez',
    email: 'ana.martinez@example.com',
    phoneNumber: '1234567890',
    age: 29,
    gender: 'Female',
    paymentMethod: 'paypal',
    travelId: 1,
    notes: 'Prefers direct flights.',
  },
  {
    id: 2,
    firstName: 'Luis',
    lastName: 'González',
    email: 'luis.gonzalez@example.com',
    phoneNumber: '0987654321',
    age: 35,
    gender: 'Male',
    paymentMethod: 'revolut',
    travelId: 2,
  },
  {
    id: 3,
    firstName: 'María',
    lastName: 'Rodríguez',
    email: 'maria.rodriguez@example.com',
    phoneNumber: '1122334455',
    age: 22,
    gender: 'Female',
    paymentMethod: 'bank transfer',
    travelId: 3,
    notes: 'Allergic to peanuts.',
  },
  {
    id: 4,
    firstName: 'Jorge',
    lastName: 'López',
    email: 'jorge.lopez@example.com',
    phoneNumber: '5566778899',
    age: 28,
    gender: 'Male',
    paymentMethod: 'paypal',
    travelId: 4,
  },
  {
    id: 5,
    firstName: 'Sofía',
    lastName: 'Pérez',
    email: 'sofia.perez@example.com',
    phoneNumber: '2233445566',
    age: 31,
    gender: 'Female',
    paymentMethod: 'revolut',
    travelId: 5,
    notes: 'Vegetarian meal preference.',
  },
  {
    id: 6,
    firstName: 'Carlos',
    lastName: 'Navarro',
    email: 'carlos.navarro@example.com',
    phoneNumber: '6677889900',
    age: 27,
    gender: 'Male',
    paymentMethod: 'Bank transfer',
    travelId: 1,
  },
  {
    id: 7,
    firstName: 'Beatriz',
    lastName: 'Díaz',
    email: 'beatriz.diaz@example.com',
    phoneNumber: '9988776655',
    age: 34,
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 2,
    notes: 'Requires wheelchair access.',
  },
  {
    id: 8,
    firstName: 'David',
    lastName: 'Jiménez',
    email: 'david.jimenez@example.com',
    phoneNumber: '5544332211',
    age: 45,
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 3,
  },
  {
    id: 9,
    firstName: 'Elena',
    lastName: 'Suárez',
    email: 'elena.suarez@example.com',
    phoneNumber: '1122443355',
    age: 26,
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 4,
    notes: 'Prefers aisle seat.',
  },
  {
    id: 10,
    firstName: 'Fernando',
    lastName: 'Torres',
    email: 'fernando.torres@example.com',
    phoneNumber: '5566887799',
    age: 32,
    gender: 'Male',
    paymentMethod: 'Paypal',
    travelId: 5,
  },
  {
    id: 11,
    firstName: 'Gabriela',
    lastName: 'Luna',
    email: 'gabriela.luna@example.com',
    phoneNumber: '6655443322',
    age: 29,
    gender: 'Female',
    paymentMethod: 'Revolut',
    travelId: 1,
  },
  {
    id: 12,
    firstName: 'Héctor',
    lastName: 'Vega',
    email: 'hector.vega@example.com',
    phoneNumber: '2233554477',
    age: 37,
    gender: 'Male',
    paymentMethod: 'Bank transfer',
    travelId: 2,
  },
  {
    id: 13,
    firstName: 'Irene',
    lastName: 'Molina',
    email: 'irene.molina@example.com',
    phoneNumber: '7788990011',
    age: 25,
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 3,
    notes: 'Non-smoker.',
  },
  {
    id: 14,
    firstName: 'Javier',
    lastName: 'Herrera',
    email: 'javier.herrera@example.com',
    phoneNumber: '8899001122',
    age: 39,
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 4,
  },
  {
    id: 15,
    firstName: 'Laura',
    lastName: 'Sánchez',
    email: 'laura.sanchez@example.com',
    phoneNumber: '4455667788',
    age: 33,
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 5,
    notes: 'Vegan meals only.',
  },
]
