export default [
  {
    id: 1,
    firstName: 'Marta',
    lastName: 'Jamardo',
    email: 'marta.jamardo@example.com',
    phoneNumber: '123-456789',
    birthDate: '28/05/1990',
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 1,
    notes: 'Prefers direct flights.',
  },
  {
    id: 2,
    firstName: 'Miguel',
    lastName: 'Fernandez',
    email: 'miguel.fernandez@example.com',
    phoneNumber: '098-765432',
    birthDate: '22/11/1987',
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 2,
  },
  {
    id: 3,
    firstName: 'Martina',
    lastName: 'Barbati',
    email: 'maria.barbati@example.com',
    phoneNumber: '112-233445',
    birthDate: '05/07/1990',
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 3,
    notes: 'Allergic to mushrooms.',
  },
  {
    id: 4,
    firstName: 'Jorge',
    lastName: 'López',
    email: 'jorge.lopez@example.com',
    phoneNumber: '556-677889',
    birthDate: '09/02/1996',
    gender: 'Male',
    paymentMethod: 'Paypal',
    travelId: 4,
  },
  {
    id: 5,
    firstName: 'Sofía',
    lastName: 'L',
    email: 'sofia.l@example.com',
    phoneNumber: '223-344556',
    birthDate: '12/12/1993',
    gender: 'Female',
    paymentMethod: 'Revolut',
    travelId: 5,
    notes: 'Vegetarian meal preference.',
  },
  {
    id: 6,
    firstName: 'Carlos',
    lastName: 'Navarro',
    email: 'carlos.navarro@example.com',
    phoneNumber: '667-788990',
    birthDate: '27/04/1997',
    gender: 'Male',
    paymentMethod: 'Bank transfer',
    travelId: 1,
  },
  {
    id: 7,
    firstName: 'Natalie',
    lastName: 'Hughes',
    email: 'natalie.hughes@example.com',
    phoneNumber: '998-877665',
    birthDate: '17/03/1992',
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 2,
    notes: 'Requires wheelchair access.',
  },
  {
    id: 8,
    firstName: 'David',
    lastName: 'Jiménez',
    email: 'david.jimenez@example.com',
    phoneNumber: '554-433221',
    birthDate: '29/06/1978',
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 3,
  },
  {
    id: 9,
    firstName: 'Elena',
    lastName: 'Suárez',
    email: 'elena.suarez@example.com',
    phoneNumber: '112-244335',
    birthDate: '15/05/1998',
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 4,
    notes: 'Prefers aisle seat.',
  },
  {
    id: 10,
    firstName: 'Fernando',
    lastName: 'Torres',
    email: 'fernando.torres@example.com',
    phoneNumber: '556-688779',
    birthDate: '03/08/1992',
    gender: 'Male',
    paymentMethod: 'Paypal',
    travelId: 5,
  },
  {
    id: 11,
    firstName: 'Gabriela',
    lastName: 'Luna',
    email: 'gabriela.luna@example.com',
    phoneNumber: '665-544332',
    birthDate: '19/09/1994',
    gender: 'Female',
    paymentMethod: 'Revolut',
    travelId: 1,
  },
  {
    id: 12,
    firstName: 'Hector',
    lastName: 'Godoy',
    email: 'hector.godoy@example.com',
    phoneNumber: '223-355447',
    birthDate: '07/02/1986',
    gender: 'Male',
    paymentMethod: 'Bank transfer',
    travelId: 2,
  },
  {
    id: 13,
    firstName: 'Irene',
    lastName: 'Molina',
    email: 'irene.molina@example.com',
    phoneNumber: '778-899001',
    birthDate: '20/10/1999',
    gender: 'Female',
    paymentMethod: 'Paypal',
    travelId: 3,
    notes: 'Non-smoker.',
  },
  {
    id: 14,
    firstName: 'Fco. Javier',
    lastName: 'Sanchez',
    email: 'javier.sanchez@example.com',
    phoneNumber: '889-900112',
    birthDate: '04/07/1985',
    gender: 'Male',
    paymentMethod: 'Revolut',
    travelId: 4,
  },
  {
    id: 15,
    firstName: 'Laura',
    lastName: 'Sánchez',
    email: 'laura.sanchez@example.com',
    phoneNumber: '445-566778',
    birthDate: '18/08/1991',
    gender: 'Female',
    paymentMethod: 'Bank transfer',
    travelId: 5,
    notes: 'Vegan meals only.',
  },
]
